In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import numpy as np # using NumPy

**Creating NumPy Arrays From Python List**

In [3]:
my_list = [0,1,2,3,4,5,6,7,8,9,10]

In [4]:
nparr = np.array(my_list)
print(nparr)

[ 0  1  2  3  4  5  6  7  8  9 10]


**Or From Built-in Method**

In [6]:
nparr=np.arange(0,15)
print(nparr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


**Universal Function - ufunc**
 
 Arithmetic Operations we can perform with NumPy Arrays

In [7]:
nparr_added = nparr + nparr
print(nparr_added)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [9]:
nparr_sub = nparr - nparr
print(nparr_sub)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [12]:
nparr_mult = nparr * nparr
print(nparr_mult)

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196]


In [13]:
nparr_div = nparr / nparr
print(nparr_div)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [15]:
nparr_esc = nparr * 10
print(nparr_esc)              # multiply by a scalars

[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140]


In [17]:
nparr_one_div = 1/nparr
print(nparr_one_div)

#one divided by zero
#inf signifies infinity for one divided by zero at the very first element

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909
 0.08333333 0.07692308 0.07142857]


In [18]:
#Exponent - Arrays - Squaring everything - Two options
np_arr_exp1 = nparr ** 2
print(np_arr_exp1)

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196]


In [19]:
np_arr_exp2 = np.square(nparr) 
print(np_arr_exp2)

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196]


In [20]:
nparr_sr = np.sqrt(nparr)   # Square Root
print(nparr_sr)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]


In [21]:
nparr_sr = np.sqrt(np_arr_exp1) 
print(nparr_sr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


In [22]:
nparr_sr = np.sqrt(np_arr_exp2) 
print(nparr_sr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


In [23]:
#Exponential With Arrays
np_arr_exp3 = np.exp(nparr) 
print(np_arr_exp3)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06]


In [24]:
nparr_max = np.max(nparr)
print(nparr_max)             #Maximum

14


In [25]:
nparr_min = np.min(nparr)
print(nparr_min)              #Minimum

0


In [26]:
#Trigonometric Functions - Passing every element into since function
nparr_sin = np.sin(nparr)
print(nparr_sin)

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021
 -0.53657292  0.42016704  0.99060736]


In [27]:
#Logarithmic - Note: the very first one is minus infinity
nparr_log = np.log(nparr)
print(nparr_log)

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527
 2.48490665 2.56494936 2.63905733]


**Numpy Practicing Exercises:-**

**1. Create an Array of the integers from 10 to 50**

In [28]:
arr_10to50 = np.arange(10,51)
print(arr_10to50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


**2. Create an Array of the Even integers from 10 to 50**

In [34]:
arr_10to50_even = np.arange(10,51,2)
print(arr_10to50_even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


**3. Create an Array of the Odd integers from 11 to 51**

In [37]:
arr_11to51_odd = np.arange(11,52,2)
print(arr_11to51_odd)

[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51]


**4. Create a 3x3 matrix with values ranging from 1 to 9**

In [38]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
np.arange(6,15).reshape(3,3)

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [50]:
np.arange(4,12).reshape(4,2)

array([[ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [53]:
np.arange(4,10).reshape(2,3)

array([[4, 5, 6],
       [7, 8, 9]])

In [65]:
arr1=np.arange(0,8).reshape(2,4)
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [67]:
arr1.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

**5. Use NumPy to generate a random number between 0 and 1**

In [58]:
np.random.rand(1)

array([0.23157064])

**6. Use NumPy to generate 25 random numbers sampled from a standard normal distribution**

In [59]:
np.random.rand(25)

array([0.8867224 , 0.7003701 , 0.9995269 , 0.06392683, 0.01109143,
       0.01937587, 0.33667636, 0.32628313, 0.22365454, 0.23490587,
       0.48042496, 0.94527258, 0.24127254, 0.59776094, 0.94994879,
       0.0847822 , 0.23859484, 0.02367677, 0.05335627, 0.7757987 ,
       0.99448864, 0.49662014, 0.63162793, 0.92969035, 0.57922127])

**7. Create a matrix of 100 items spaced equally at 0.01 steps ranged from 0.01 to 1**

In [60]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [62]:
np.linspace(0.01,1,100).reshape(10,10)  #Returning the exact same result as above

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

**8. Create an Array of 20 linearly spaced points between 0 and 1**

In [63]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

**Thank You**